In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv('data_jabatan.csv')
dataset.sample(5)

NameError: name 'pd' is not defined

In [3]:
X = dataset.iloc[:,[2,3]].values
y = dataset.iloc[:,[-1]].values
x=dataset

NameError: name 'dataset' is not defined

In [98]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [99]:
X_train.shape

(6, 2)

In [100]:
y_train.shape

(6, 1)

In [101]:
X_test.shape

(3, 2)

In [102]:
y_test.shape

(3, 1)

In [103]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)
X_test

array([[ 0.26726124,  1.39464858],
       [-1.33630621, -0.49430583],
       [ 1.06904497, -0.90034276]])

In [104]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

C:\Users\asus\anaconda3\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


LogisticRegression(random_state=0)

In [105]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 0], dtype=int64)

In [106]:
y_actual = y_test.flatten()
y_actual

array([0, 1, 1], dtype=int64)

In [107]:
for i in range(len(y_actual)):
    print(f'Hasil aktual: {y_actual[i]} hasil prediksi: {y_pred[i]}')

Hasil aktual: 0 hasil prediksi: 0
Hasil aktual: 1 hasil prediksi: 0
Hasil aktual: 1 hasil prediksi: 0


In [110]:
# Visualising the Test set results
from matplotlib.colors import ListedColormap
X_set, y_set = X_test, y_test
X1, X2 = np.meshgrid(np.arange(start = X_set[:, 0].min() - 1, stop = X_set[:, 0].max() + 1, step = 0.01),
                     np.arange(start = X_set[:, 1].min() - 1, stop = X_set[:, 1].max() + 1, step = 0.01))
plt.contourf(X1, X2, classifier.predict(np.array([X1.ravel(), X2.ravel()]).T).reshape(X1.shape),
             alpha = 0.55, cmap = ListedColormap(('blue', 'red')))
plt.xlim(X1.min(), X1.max())
plt.ylim(X2.min(), X2.max())
for i, j in enumerate(np.unique(y_set)):
    plt.scatter(X_set[y_set == j, 0], X_set[y_set == j, 1],
                c = ListedColormap(('blue', 'red'))(i), label = j)
plt.title('Logistic Regression (Test set)')
plt.xlabel('umur')
plt.ylabel('gaji')
plt.legend()
plt.show()

NameError: name 'plt' is not defined